server:
  port: 8020

spring:
  application:
    name: census-fwmt-job-service
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    user:
      name: "user"
      password: "password"
  redis:
    host: "localhost"
    port: 6379
    password: "password"

management:
  # Place /info and /health in the root
  endpoints.web.base-path: ''
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    uk.gov.ons.fwmt: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
  file: target/SpringErrors/spring.log
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] [%X{FILENAME}] %logger{1}::%M - %msg%n"
    file:    "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{CID}] [%X{FILENAME}] %logger{1}::%M - %msg%n"

rabbitmq:
  username: "guest"
  password: "guest"
  hostname: "localhost"
  port: 5672
  virtualHost: "/"
  initialinterval: 5000
  multiplier: 3.0
  maxInterval: 45000

totalmobile:
  username: "user"
  password: "password"
  baseUrl: "http://localhost:8000/"
  comet:
    clientID: ""
    clientSecret: ""
  operation:
    case:
      create:
        path: "cases/"

fwmt:
  workTypes:
    ccs:
      duration: 5
    ce:
      duration: 5
    hh:
      duration: 5
    ohs:
      duration: 5